title: Software Development Project 1
email: kalle.ilves@haaga-helia.fi
description: >-
  Course page for the Software Development Project 1 course
baseurl: ""
url: ""
theme: just-the-docs
plugins:
  - jekyll-feed
callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Important!
    color: red
  highlight:
    title: Heads-up
    color: yellow
  note:
    title: Note
    color: purple
teacher_text: "Kalle Ilves (kalle.ilves@haaga-helia.fi)"
teaching_sessions_text: "on Mondays at 11:00 - 13:00 and Thursdays at 14:00 - 16:00 in classroom 5006 for the implementation SOF005AS3A-3014 and on Mondays at 8:00 - 10:00 and Wednesdays at 8:45 - 10:45 in classroom 4009 for the implementation SOF005AS3AE-3003"
moodle_link: "https://hhmoodle.haaga-helia.fi/course/view.php?id=42164"
teams_flinga_link: "https://edu.flinga.fi/s/E4M68AC"
week_1_deadline: "28.10. at 8:00"
week_2_deadline: "4.11. at 8:00"
sprint_1_deadline: "18.11. at 8:00"
sprint_2_deadline: "2.12. at 8:00"
sprint_3_deadline: "15.12. at 23:59"
sprint_1_user_story_1: "As a teacher, I want to add a quiz so that students can learn about course-related topics"
sprint_1_user_story_2: "As a teacher, I want to see a list of added quizzes so that I know which quizzes are added"
sprint_1_user_story_3: "As a teacher, I want to edit a quiz so that I can change its information"
sprint_1_user_story_4: "As a teacher, I want to delete a quiz so that I can get rid of quizzes I don't need"
sprint_1_user_story_5: "As a teacher, I want to add a question to a quiz so that students can learn about course-related topics"
sprint_1_user_story_6: "As a teacher, I want to see a list of quiz's questions so that I know which questions the quiz has"
sprint_1_user_story_7: "As a teacher, I want to delete a quiz's question so that I can get rid of questions I don't need"
sprint_1_user_story_8: "As a teacher, I want to add an answer option to a question so that students can learn about course-related topics"
sprint_1_user_story_9: "As a teacher, I want to see a list of questions's answer options so that I know which answer options the question has"
sprint_1_user_story_10: "As a teacher, I want to delete an answer option so that I can get rid of answer options I don't need"
sprint_2_user_story_1: "As a teacher, I want to add a category so that I can categorize quizzes"
sprint_2_user_story_2: "As a teacher, I want to see a list of added categories so that I know which categories are added"
sprint_2_user_story_3: "As a teacher, I want to choose a category for a quiz so that I can categorize quizzes"
sprint_2_user_story_4: "As a teacher, I want to delete a category so that I can get rid of categories I don't need"
sprint_2_user_story_5: "As a student, I want to see a list of published quizzes so that I know which quizzes I can take"
sprint_2_user_story_6: "As a student, I want to see the questions of a quiz so that I know the contents of the quiz"
sprint_2_user_story_7: "As a student, I want to answer the questions of a quiz so that I can know if my answers are correct"
sprint_2_user_story_8: "As a user, I want to see the number of correct and wrong aswers of each question of a quiz so that I can know the results of a quiz"
sprint_2_user_story_9: "As a student, I want to see a list of added categories so that I can browse quizzes in different categories"
sprint_2_user_story_10: "As a student, I want to see a list of quizzes of a category so that I can browse the quizzes of a category"
sprint_3_user_story_1: "As a student, I want to review a quiz so that I can share my thoughts about the quiz with others"
sprint_3_user_story_2: "As a student, I want to see the reviews of a quiz so that I can learn what others think about the quiz"
sprint_3_user_story_3: "As a student, I want to delete a review so that I can get rid of reviews I don't need"
sprint_3_user_story_4: "As a student, I want to edit a review so that I can change its information"
sprint_3_user_story_5: "As a student, I want to filter the questions of quiz by the difficulty level so that I can easily find suitable questions for my skill level"
