title: Software Development Project 1
email: kalle.ilves@haaga-helia.fi
description: >-
  Course page for the Software Development Project 1 course
baseurl: ""
url: ""
theme: just-the-docs
plugins:
  - jekyll-feed
callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Important!
    color: red
  highlight:
    title: Heads-up
    color: yellow
  note:
    title: Note
    color: purple
teacher_text: "Kalle Ilves (kalle.ilves@haaga-helia.fi)"
teaching_sessions_text: "Thursdays at 14:00 - 16:45 in classroom 4012"
moodle_link: "https://hhmoodle.haaga-helia.fi/course/view.php?id=38762"
week_1_moodle_submission_link: "https://hhmoodle.haaga-helia.fi/mod/assign/view.php?id=2634199"
week_2_moodle_submission_link: "https://hhmoodle.haaga-helia.fi/mod/assign/view.php?id=2634203"
sprint_1_moodle_submission_link: "https://hhmoodle.haaga-helia.fi/mod/assign/view.php?id=2634208"
example_project_link: "https://github.com/software-development-project-1/example-project"
week_1_deadline: "2.11. at 10:00"
week_2_deadline: "9.11. at 10:00"
sprint_1_deadline: "23.11. at 10:00"
sprint_2_deadline: "7.12. at 10:00"
sprint_3_deadline: "17.12. at 23:59"
sprint_1_user_story_1: "As a teacher, I want to add a quiz so that my students can learn about course-related topics"
sprint_1_user_story_2: "As a teacher, I want to see a list of added quizzes so that I know which quizzes are added"
sprint_1_user_story_3: "As a teacher, I want to be able to edit a quiz so that I can change its information"
sprint_1_user_story_4: "As a teacher, I want to be able to delete a quiz so that I can get rid of quizzes I don’t need"
sprint_1_user_story_5: "As a teacher, I want to be able to filter quizzes based on the published status so that I can easily find quizzes with a specific published status"
sprint_1_user_story_6: "As a teacher, I want to know the date when a quiz was added so that I know how old it is"
sprint_1_user_story_7: "As a teacher, I want the quizzes to be listed from newest to oldest so that I can find the latest quizzes quickly"
sprint_2_user_story_1: "As a teacher, I want to add a question to a quiz so that my students can learn about course-related topics"
sprint_2_user_story_2: "As a teacher, I want to see a list of quiz's questions so that I know which questions the quiz has"
sprint_2_user_story_3: "As a teacher, I want to delete a quiz's question so that I can get rid of questions I don’t need"
sprint_2_user_story_4: "As a teacher, I want to to able to filter quiz's questions based on the difficulty level so that I can easily find questions with a specific difficulty level"
sprint_2_user_story_5: "As a student, I want to see a list of published quizzes so that I know which quizzes I can take"
sprint_2_user_story_6: "As a student, I want to see the questions of a quiz so that I know the contents of the quiz"
sprint_2_user_story_7: "As a student, I want to answer the questions of a quiz so that I can know if my answers are correct"
sprint_3_user_story_1: "As a user, I want to see the number of correct and wrong aswers of each question of a quiz so that I can know the results of a quiz"
sprint_3_user_story_2: "As a teacher, I want to register an account so that I can manage my personal quizzes"
sprint_3_user_story_3: "As a teacher, I want to sign in so that I can manage my personal quizzes"
sprint_3_user_story_4: "As a teacher, I want to associate the added quiz with my account so that I can manage my personal quizzes"
