title: Software Development Project 1
email: kalle.ilves@haaga-helia.fi
description: >-
  Course page for the Software Development Project 1 course
baseurl: ""
url: ""
theme: just-the-docs
plugins:
  - jekyll-feed
callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Important!
    color: red
  highlight:
    title: Heads-up
    color: yellow
  note:
    title: Note
    color: purple
week_1_moodle_submission_link: "#"
week_2_moodle_submission_link: "#"
sprint_1_moodle_submission_link: "#"
example_project_link: "#"
teacher_email: "kalle.ilves@haaga-helia.fi"
week_1_deadline: "2.11. at 10:00"
week_2_deadline: "9.11. at 10:00"
sprint_1_deadline: "23.11. at 10:00"
sprint_2_deadline: "7.12. at 10:00"
sprint_3_deadline: "19.12. at 10:00"